### ISSUE TITLE
Having a global process using Swarm

### ISSUE THREAD

**Issue by FabienHenon** [bitwalker/swarm#66] opened 2018-02-02 16:26 UTC
Hi,

Maybe my use case is not adapted to the way we should use Swarm but I thought it could be worth trying.

What I would like is:
- Having a global process across my nodes (let's say a counter, but it could be a process with more complicated state and logic)
- I need to be able to increment that counter from any node and getting the result from the counter from any node
- I need to launch this process at application startup
- When I start a new node (a counter is created at startup) and connect it to the cluster I want to keep only ONE counter in the entire cluster and kill the other 
- But I also need my dying counter to be able to tell the other counter what is his state, so that the other counter can choose to merge it with his own state
- Finally, when I kill the node hosting the counter I need that counter to be recreated on another node with his current state

I first thought about naming my counter with `{:global, :counter}` but as soon as I connect 2 nodes together all counters die because of the already globally registered counter.

Then I tried with Swarm. I started my counter and registered it to Swarm like this:

```elixir
def start_link(_) do
    case Swarm.register_name(__MODULE__, __MODULE__, :register, []) do
      {:ok, pid} ->
        Swarm.join(:notification_sender, pid)
        {:ok, pid}

      {:error, reason} ->
        {:error, reason}
    end
  end

  def register() do
    GenServer.start_link(__MODULE__, 0)
  end
```

The `start_link` function being called by the main `Supervisor`.
This is working almost fine! When I start a node a counter is created, and when I connect 2 nodes together, only one counter is kept.
However, this does not solve my 2 last points: give the state of the dying counter to the other counters and recreate a counter with a correct state (like when returning `:resume` during handoff).

Is there any solution with Swarm for this? Or using any other OTP feature?

If there is no solution I may try something different like keeping one counter per node in the same swarm group and broadcasting increments to each process of the group so that each counter remains synchronized. Is it a better solution? Should I register a process using `Swarm.register_name(name, pid)` so that my counters stay in their own node? Or is there a solution to keep my counters in their parent node?

Thank you for your help!

**Comment by mbaeuerle** [comment] 2018-02-06 09:43
> - But I also need my dying counter to be able to tell the other counter what is his state, so that the other counter can choose to merge it with his own state

If the node crashes it is not able to tell any other node the current state because a crash is instant (and could be caused by the hardware). There might be a way if the node shuts down gracefully like this issue suggests #11. So I think the best way to achieve this is either as you said synchronizing the state across the nodes. Keep in mind that they are eventually consistent and there might be a situation where the counter is updated on two nodes simultaneously leading to an inconsistency.

The other way I see is to use one single swarm worker for the counter which persists the counter in some storage on each change. When the node crashes another node is spawned using the persistent storage to recover the counter. This may not scale very well but should not cause any inconsistencies.

**Comment by bitwalker** [comment] 2018-02-07 20:23
If the process and the node it is on is stable (i.e. not crashing), you can just use Swarm's handoff mechanism to ensure state is merged the way you want (and you could use a counter CRDT as the state of that process to provide a means by which you could resolve conflicts after a network partition, if they occur). That said, if persistence and consistency is crucial, you are likely better off using Mnesia (or some other external data store) and storing your counter there. In short, Swarm may or may not be the right tool for this, depending on your requirements.

The suggestion by @mbaeuerle to store the counter in ETS (for persistence across process crashes) or something distributed/external (mnesia, redis, etc) as a means by which it can restore it's state in the case of a crash is a good one, and the only means by which you will be persistent across node crashes.

**Closed by bitwalker** 2018-02-07 20:23 UTC

**Comment by FabienHenon** [comment] 2018-02-07 21:19
Thank you both for your answers. I'll try to look for simple solutions with state synchornization across nodes and if it seems to difficult/complex, I'll have a try mith mnesia :)
