### ISSUE TITLE
Purposeful node failover

### ISSUE THREAD

**Issue by timbuchwaldt** [bitwalker/swarm#35] opened 2017-06-08 06:54 UTC
Hi! Swarm looks awesome, I just miss one feature: Manually telling swarm to failover everything that it manages on one node.
This could basically be what happens on addition of a new node, but reversed and would allow for more seamless upgrades of nodes, downscaling if the load is going down and so on.

Is this something that fits your idea for swarm?

**Comment by bitwalker** [comment] 2017-06-08 06:57
Definitely! It should be pretty straightforward to implement, I'll add it to my TODO list

**Comment by mbaeuerle** [comment] 2018-03-19 18:07
I tried to tackle this issue [here](https://github.com/bitwalker/swarm/compare/master...semlabs:feature/graceful-shutdown). 

My thoughts:
- Create a function which allows for manual handoff of a specific worker (in this case `handoff` but the naming is to be discussed). It Takes the name of the worker to be moved and the current state
- The Tracker is retrieving the entry of the actual worker
- It then checks the strategy on which other node the worker should be placed (by removing the current node [here](https://github.com/bitwalker/swarm/compare/master...semlabs:feature/graceful-shutdown#diff-9a740675aac0f251436d9457d40a3153R1017))
- If there is another node to move the worker's state it's done in a similar way like on a cluster resize

- The handoff call can then be placed in the workers `terminate/2` function when `:trap_exit` is flagged. When receiving a `SIGTERM` this should trigger the handoff of the current state

Parts I am not sure about:
- I don't know if I handled the clock correctly
- I am unsure if temporarily removing the current node before `Strategy.key_to_node/1` leaves any inconsistencies in the registry which lead to a broken state

@bitwalker let me know what you think about it.

**Comment by hickscorp** [comment] 2018-04-02 17:53
Trying to understand something here and it's really unclear whether or not it is possible. Once several nodes are running, and distribution of processes already has occured for a while, is it possible to shutdown one of these nodes while having state handover?

Right now, we only have our state handover when nodes are *joining*. When using `:init.stop` on a node, it doesn't handover any of the processes on other nodes. Is that expected behaviour?

**Comment by mbaeuerle** [comment] 2018-04-03 10:05
@hickscorp that's what the issue is all about. At the moment it is not possible to handover the current state of a node which is about to shut down. But it is a feature hopefully coming in the near future!

**Comment by arjan** [comment] 2018-07-05 07:19
Ping! Need this as well :-)

**Comment by arjan** [comment] 2018-07-16 12:38
Been using @mbaeuerle's solution and it works pretty well for me. I dont use the terminate callback, but just trigger the handoff for each local process manually before shutting down the node.

**Comment by arjan** [comment] 2018-09-20 20:17
This issue has been addressed now that #83 has been merged. 

Basically, you can iterate over all registered processes, filter out the names that are registered to local pids, and perform `Swarm.Tracker.handoff/2` on these, to have them migrate to other nodes, after which it is safe to shut down the current node.

**Closed by arjan** 2018-09-20 20:17 UTC
Labels: feature
