### ISSUE TITLE
Deadlock when registering process

### ISSUE THREAD

**Issue by szlend** [bitwalker/swarm#4] opened 2016-08-29 21:07 UTC
First off, great job on the library! I can't believe how easy it was to incorporate it into my project. There is one issue that I found though. When spawning lots of processes very rapidly across multiple nodes, I often run into a deadlock. I've tracked the issue to this line

https://github.com/bitwalker/swarm/blob/ec943bde2e5741e5a475b8bbe42f433645da9f06/lib/swarm/tracker.ex#L123

It seems both nodes try to call each other's Swarm.Tracker at the same time and time out when none of them can reply.

**Comment by szlend** [comment] 2016-08-30 20:36
I made a quick fix by deferring the GenServer.call

```elixir
spawn_link(fn ->
  res = GenServer.call({__MODULE__, node}, {:register, name, mfa, groups}, 5_000)
  GenServer.reply(from, res)
end)
{:noreply, state}
```

It's probably not the way to go, I just wanted to see if that solves the issue. Is there any particular reason that registration has to go through the Swarm.Tracker GenServer?

**Comment by bitwalker** [comment] 2016-09-01 13:58
Ah good catch, that is indeed the problem. Registrations go through the tracker process in order to enforce serialized writes to the registry, but the more I think about it, the less I think it may be necessary. I'm at ElixirConf right now, so I have limited time to tackle this, but I'll get a fix released as soon as possible.

**Comment by szlend** [comment] 2016-09-01 15:10
Thanks! Though, don't you already enforce serialized writes through the Swarm.ETS GenServer?

**Comment by bitwalker** [comment] 2016-09-10 06:33
@szlend I'm getting ready to merge a set of changes which rework a lot of the internals. Would you be willing to give the `pubsub` branch a shot? You should be able to just swap out your dependency with `{:swarm, github: "bitwalker/swarm", branch: "pubsub"}` to try it out.

Your original issue has been addressed there, I just want to be sure the new branch works as expected for more than just myself before I merge into master and release it.

**Comment by szlend** [comment] 2016-09-10 11:12
Thanks for tackling this one!  Here's some quick feedback, I'll try and do some more proper testing this weekend.

1. I needed to replace the process name with a binary (it was a tuple before). I'm guessing this is due to Phoenix PubSub. It's not a problem for me, just something I noticed.
2. Every so often I get this error when running my application. It seems to happen completely random.
`The on_load function for module crypto returned {:error, {:load, 'Library load-call unsuccessful.'}}`. This one is really weird cause I can load and use `:crypto`just fine on it's own in iex.
3. I'm not so sure that automatic conflict resolution is that great for my use case. Or maybe I just don't understand how I'm supposed to handle it properly. How can I ensure I don't lose any process state in case of a conflict? 
4. I did eventually run into a timeout when registering the process. But it's possible that I completely flooded the scheduler. I'll try and do some more proper tests later.

**Comment by bitwalker** [comment] 2016-09-10 17:01
@szlend Thanks for the feedback! A couple notes:

1. A tuple should be supported, I was testing with atoms, but I must've missed something, I'll get that fixed right away.
2. I don't know that this is related to Swarm specifically. `:ssl` is in the applications list of Swarm, which depends on `:crypto`, but the error is likely due to something in your environment I think. That said, I don't need to have `:ssl` in Swarm, so I can remove it.
3. There is documentation on how to handle the `{:swarm, :begin_handoff}` call, if you don't want Swarm to move processes around you can return `:ignore`, but they will be restarted if the node they live on dies or becomes unavailable. In the case of a network partition, the most recent registration wins (since it would be the one which places the process on the right node), however I can probably add an option to prevent doing so in cases where you don't want Swarm to do anything with those processes other than the initial distribution.
4. Could you give me any numbers on how many processes you were registering and how fast? Were you dropping/adding nodes during this as well? That will help me figure out where the bottleneck may be. I haven't done heavy stress testing on it yet myself, though I will be very soon, since I was trying to make sure it worked correctly before making it scale, but there are a few places I can think of which may be causing bottlenecks.

Thanks again for the help! I'll be pushing those changes I mentioned today :)

**Comment by szlend** [comment] 2016-09-10 18:24
1. Great!

2. It appears to be a bug with Erlang/OpenSSL. If you start `:crypto` after`:observer`, it fails to load OpenSSL. I reported the issue on the Erlang bug tracker.

3. What happens if the old process receives a message in the middle of a handoff? I'm guessing this won't be forwarded to the new process right? Do I have to handle such edge cases by myself?

4. Thousands of processes and probably hundreds of processes per second. I was writing a distributed minesweeper grid, with each 100x100 section being it's own process. I lazily spawn more sections as you reveal tiles on the edge of each section. Then to stress test the communication between the sections, I set the section size to 2x2 and ran the reveal function on an almost empty grid, so it expands into infinity. I didn't add or remove any nodes during the stress test.

**Comment by szlend** [comment] 2016-09-10 18:54
Also for fun, here's the comparison of scheduler utilization between versions.

0.4 https://i.imgur.com/x252OmK.png
0.5 https://i.imgur.com/8cdNCb7.png

**Comment by bitwalker** [comment] 2016-09-10 20:41
That's very interesting, looks like average utilization is probably about the same, but the new version is much more bursty. Also interesting that the memory and IO usage is much lower in the new version.

2. Oh that's very interesting, I haven't hit that one before, well done figuring it out!

3. That is up to the consumer of the API for now, in my case it doesn't matter, and the window for problems to arise is very short, as immediately after getting the response from handle_call, `{:swarm, :die}` is sent to the process. There is probably a way to do the response and shutdown in one shot, I know I can think of a way off the top of my head (using the approach in your workaround, reply asynchronously and return `{:stop, :shutdown, nil}` to kill the process and prevent handling any further messages).

4. Ok that's good to know, I'll do some testing and see if I can reproduce, probably will be sometime tomorrow.

Thanks again for the help!

**Comment by szlend** [comment] 2016-09-10 23:50
I also noticed that in my case it's creating a ton of duplicate processes/registrations that it later has to resolve (kill). Even with a single node. I don't think Phoenix Presence is that great for registering processes on the same node, because it introduces an unnecessary race condition between spawning and registration. Would it be possible to write local registrations into ETS immediately? That way you don't have any conflicts with spawning, and you can use Presence only to sync registrations and handle node changes. Or am I missing some potential issues with that?

**Comment by bitwalker** [comment] 2016-09-22 21:38
If you're interested in trying my latest shot at rewriting the internals, it's on the `rewrite` branch. It's missing process groups at the moment, though that's by far the easiest thing to add, and there are a few edge cases around conflict resolution I have on my todo list, but haven't yet implemented fixes for, but in the general case it should work much better, and I'd be interested to see how it works with other's use cases. Any feedback is helpful :)

**Comment by szlend** [comment] 2016-09-22 21:55
Awesome, I'll try and have a look this weekend :)

**Comment by bitwalker** [comment] 2016-09-23 19:33
Just FYI, I've changed the branch to `develop`, so you don't wonder why `rewrite` is missing :)

**Comment by szlend** [comment] 2016-09-25 14:36
I just wrote a small benchmark for swarm. It's similar to what I do in my project, but a lot worse. Basically what it does is it starts a process called `n` and then it tires to ping `m` (n-1, n+1, n-2, n+2, ...) amount of processes around it. And if the process doesn't exist, it lazily spawns it. The next process then repeats that until it reaches a certain depth.

It seems to work fine with just one node, but as soon as I add another it just keeps spawning processes until it runs out of resources. Though maybe it's because I haven't handled conflict resolution. It's weird though cause it doesn't print a single line when distributed.

I don't know if this is a very realistic case that you want to handle, but on my project I currently use `syn`and `hash_ring` and it seems to handle that kind of workload fine.

https://github.com/szlend/swarm_test

I hope this helps you in any way :)

**Comment by bitwalker** [comment] 2016-09-25 15:22
@szlend Thanks :). I'm still tweaking some things, so it looks like your test found a bug I need to address.

I actually tried an implementation using the same internals as `syn`, but the problem is that `mnesia` cannot handle dynamic node membership, so unless you have a fixed set of nodes, it's not an option (which is my situation).

I'll keep updating this thread as I get closer to a release!

**Comment by bitwalker** [comment] 2016-09-25 15:23
Oh, one thing you may want to do in your project is use my hash ring implementation :)

It's about 10x faster than `hash_ring`, and is based on the same algorithm. The only difference is that you need to maintain the hash ring state in your own process (I don't wrap it in a GenServer because going through a process is a bottleneck I wished to avoid).

**Comment by szlend** [comment] 2016-09-25 16:04
Oh cool, I'm surprised it runs so fast considering `hash_ring` was written in C! But currently my code doesn't work with adding/removing nodes anyway so maybe using a hash ring is kind of unnecessary anyway. But I'll definitely give it a shot once I start supporting that. You should really extract it into it's own library :P

**Comment by bitwalker** [comment] 2016-09-25 21:15
@szlend Yeah I was very surprised as well, either the data structure I'm using for the ring (`gb_tree`) is faster for the kinds of operations being performed than the one in `hash_ring`, or there is some other bottleneck.

I'm planning on extracting it to a separate library for sure, just not sure what to call it haha.

**Comment by bitwalker** [comment] 2016-09-25 22:31
@szlend I think I understand now why your test app is failing with multiple nodes: Swarm sends registrations to the node which is responsible for starting the process, Swarm then broadcasts the registration for replication, but the original node which received the request does not track the registration itself, it replies to the caller but waits for the broadcast to track the registration to avoid conflicts. I'm going to add an overload of register_name which takes options, one of which will be to await the broadcast to ensure the registration is replicated before replying to the caller, this would resolve the issue your app has. I'll follow up here when I've got that done  along with some testing.

**Comment by bitwalker** [comment] 2016-09-26 22:07
@szlend I just pushed changes to `develop` which fix the issues you discovered with your test app based on my test runs. Could you give it a shot and let me know what feedback you have?

**Comment by bitwalker** [comment] 2016-09-27 18:48
I'm going to close this issue now that it's grown rather large and a new release has been cut. Can you open a new one if you discover any issues with the latest release?

**Closed by bitwalker** 2016-09-27 18:48 UTC

**Comment by szlend** [comment] 2016-09-27 18:51
Sure, thanks! I'll test it out as soon as I find some free time :)
